background            #151311
foreground            #928a83
cursor                #928a83
selection_background  #49433d
color0                #151311
color1                #d05d5d
color2                #92b477
color3                #9f8361
color4                #80a0c2
color5                #b287af
color6                #66a5a0
color7                #928a83
